### ISSUE TITLE
Cannot compile any code from this repo

### ISSUE THREAD

**Issue by sotaan** [ocsigen/graffiti#5]
I tried with different versions of OCaML and also different versions of packages using OPAM but I'm unable to compile & run any kind of graffiti from this repo.
With the extended version I get this error:

``` MakeFile
    File "feed.ml", line 40, characters 11-16:
    Error: This expression has type [ `use_lwt_log_instead ]
    This is not a function; it cannot be applied.
    make: *** [_server/feed.cmo] Error 2
```

With the simple version I get this with OCaML 4.01.0:

``` MakeFile
    ocsigenserver  -c local/etc/graffiti/graffiti-test.conf
    ocsigenserver: ocsigen:main: Fatal - Error in configuration file: Unknown tag eliommodule in tag host
    make: *** [test.byte] Error 50
```

**Comment by balat** [comment]
Thank you. I keep this thread open. The next release of (eliom? ocsigen-server? ...) should hopefully solve the problem.
Also we should add this repositoty in the continuous integration platform.

**Comment by balat** [comment]
Now fixed
