### ISSUE TITLE
Add tags in the repository

### ISSUE THREAD

**Issue by Drup** [ocsigen/graffiti#7]
I think the repository should be tagged with "the last working version" for a given eliom version, and that tagged used in the tutorial.

**Comment by vasilisp** [comment]
Right. I will make a final test once we freeze the Eliom 5.0 code, and add the tag.

**Comment by vasilisp** [comment]
Done: `eliom-5.0`, ocsigen/tutorial@99f17651f8d210f214b66f26b56ed0c903d4451a .
